# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_date_birth'),
        ('books', '0003_auto_20180320_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviewers',
            field=models.ManyToManyField(through='books.Book_Review', to='login.User'),
        ),
    ]
