# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_reviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reviewers',
            field=models.ManyToManyField(through='books.Book_Review', to='login.User'),
        ),
        migrations.AlterField(
            model_name='book_review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to='books.Book'),
        ),
    ]
