# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180321_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewed_books', through='books.Book_Review', to='login.User'),
        ),
    ]
